[package]
name = "p2p-handshake"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
futures-util = { version = "0.3", features = ["sink"] }
snow = "0.9.6"
tokio = { version = "1.38", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
